In this notebook you will practice how to:
1. Calculate the determinant of a 2x2 matrix with and without using numpy.linalg
2. Calculate the determinant of a 3x3 matrix with and without using numpy.linalg
3. Calculate the inverse of a 2x2 matrix using numpy.linalg
4. Calculate the inverse of a 3x3 matrix using numpy.linalg
5. Finding the rank of a matrix using numpy

In [1]:
import numpy as np


# Calculating the determinant using numpy.linalg

In [2]:
a2 = np.array([[1,2],[3,4]])
print(a2)

[[1 2]
 [3 4]]


In [3]:
result2 =  np.linalg.det(a2)
print(result2)

-2.0000000000000004


In [4]:
a3 = np.array([[1,1,2],[2,3,1],[3,4,-5]])
print(a3)

[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


In [5]:
result3 =  np.linalg.det(a3)
print(result3)

-7.999999999999998


# Calculating the determinant of a 2x2 matrixwithout using numpy

In [6]:
def Det2(Mat):
    return Mat[0,0]*Mat[1,1] - Mat[0,1]*Mat[1,0]


print(Det2(a2))

-2


# Calculating the determinant of a 3x3 matrixwithout using numpy

One idea
1. write a function to calculate the minor matrices. (hint, use slices)
2. write a function to calculate the cofactors (this should call the first function, and the determinate function)
3. the determinate function calls the function in step two and adds the results together.

Another idea 
use recursion ==> code credit https://stackoverflow.com/questions/3819500/code-to-solve-determinant-using-python-without-using-scipy-linalg-det

In [7]:
# delete function removes a sub-array from the input array
# first argument is the original array
# second argument is the index to the sub-array to be removed
# thirs argument is the axis among which the deletion happens (0: x axis "row" and 1: y axis "column")
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

arr2 = np.delete(arr, 1, 0)
print(arr2)

arr3 = np.delete(arr, 3, 1)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [8]:
def minor(arr,i,j):
    c = arr[:]
    c = np.delete(c, (i),axis=0) #deleting the row containing the matrix minor from the original matrix copy
    return [np.delete(row, (j),axis=0) for row in (c)] # Looping on each row and deleting the column element below the minor
    

def det(arr):
    n = len(arr)
    if n == 1 :return arr[0][0]
    if n == 2 :return arr[0][0]*arr[1][1] - arr[0][1]*arr[1][0]
    sum = 0
    for i in range(0,n):                 #looping on columns of the first row (minor values)
        m = minor(arr,0,i)               # Calculating the minor's corresponding cofactor matrix
        #print("minor of 0 and",i, "is:", m)
        sum =sum + ((-1)**i)*arr[0][i] * det(m) # summing the product of the minor and the "signed" determinant of the cofactor
    return sum



print(a3)
det(a3)


[[ 1  1  2]
 [ 2  3  1]
 [ 3  4 -5]]


-8

# Calculating the inverse using numpy.linalg

In [9]:
# The inverse of 2 x 2 matrix

a2 = np.array([[1,2],[3,4]])

print (a2)
print (np.linalg.det(a2))
print(np.linalg.inv(a2))

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
# The inverse of a singular matrix

a3 = np.array([[1,2],[2,4]])

print (a3)
print (np.linalg.det(a3))
print(np.linalg.inv(a3))

[[1 2]
 [2 4]]
0.0


LinAlgError: Singular matrix

In [11]:
# The inverse of 3 x 3 matrix

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [12]:
# Inverses of several matrices can
# be computed at once

A = np.array([[[1., 2.], [3., 4.]],
              [[1, 3], [3, 5]]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[[-2.    1.  ]
  [ 1.5  -0.5 ]]

 [[-1.25  0.75]
  [ 0.75 -0.25]]]


# Calculating the inverse of a 2x2 matrixwithout using numpy

#This is your homework

1. Code a function to calculate the determinant of 2x2 matrix
2. Code a function that interchange the diagonal elements of a 2x2 matrix and inverse the sign of the off diagonal elements
3. Code a function to compute the inverse of 2x2 matrix based on the two previous functions if it exists

# Calculating the inverse of a 3x3 matrixwithout using numpy

#This is your homework ==> Use the adjoint matrix method

Coding a Python code to inverse a 3x3 matrix in order to solve a linear system (no numpy.linalg.inv allowed) with 3 constraints and 3 variables:
1. Coding a function that checks if a 3x3 matrix is invertible
2. Coding a function that generates the transpose of a 3x3 matrix
3. Coding a function that generates the matrix of minors of a 3x3 matrix
4. Coding a function that generates the matrix of cofactors of a 3x3 matrix
5. Coding a function that generates the inverse of a 3x3 matrix if it exists


# Finding the rank of a matrix using numpy

In [13]:
from numpy.linalg import matrix_rank
matrix_rank(np.eye(4)) 

4

In [14]:
a3 = np.array([[1,2],[2,4]])
matrix_rank(a3) 

1